name: Build & Upload Flatpak

on:
  push:
    branches:
      - main

jobs:
  build-flatpak:
    runs-on: ubuntu-latest  # Uses GitHub's Linux server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flatpak (User Mode)
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak
        run: |
          mkdir -p build-dir
          flatpak-builder --user --install build-dir flatpak/com.apexploit.reporocket.json --force-clean

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reporocket-flatpak
          path: build-dir
